language: ruby

# Workaround for a Travis bug that breaks Bundler in Ruby 1.9.3.
# https://github.com/travis-ci/travis-ci/issues/5239
before_install:
  - gem install bundler

env:
  - TEST_RUBYOPT_FROZEN_STRING_LITERAL=1

rvm:
  - 1.9.3
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

  exclude:
    - rvm: 1.9.3
      env:
        - TEST_RUBYOPT_FROZEN_STRING_LITERAL=1
